config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '/about', to: 'about#show'
  resources :users, only: %i[show update edit destroy]
  resources :accommodations do
    resources :exchanges, only: %i[create]
  end

  resources :exchanges, only: %i[index edit show] do
    resources :modalities, only: %i[create]
    resources :messages, only: %i[create]
  end

  resources :modalities, only: %i[update progress] do
    resources :reviews, only: %i[create update edit]
  end
end

app/models/exchange.rb
class Exchange < ApplicationRecord
  has_many :modalities, dependent: :destroy
  has_many :messages, dependent: :destroy

  def create_modality(accommodation)
    Modality.create(accommodation: accommodation, exchange: self)
  end

  def find_my_modality(current_user)
    Modality.find_by("exchange_id = ? AND accommodation_id = ?", self.id, current_user.accommodation.id)
  end

  def find_other_user(current_user)
    Modality.find_by("exchange_id = ? AND accommodation_id != ?", self.id, current_user.accommodation.id).accommodation.user
  end

  def find_other_user_modality(current_user)
    Modality.find_by("exchange_id = ? AND accommodation_id != ?", self.id, current_user.accommodation.id)
  end

  def self.build_exchanges_info(current_user)
    my_exchanges = current_user.accommodation.exchanges.sort_by { |exchange|
      exchange.messages.last&.created_at || exchange.created_at
    }.reverse
    my_exchanges.map do |exchange|
      another_modality = Modality.find_by("exchange_id = ? AND accommodation_id != ?", exchange.id, current_user.accommodation.id)
      another_user = another_modality.accommodation.user
      last_message = exchange.messages.last&.content || "Send the first message!"
      [exchange, another_user, last_message]
    end
  end
end

app/controllers/exchanges_controller.rb
require 'date'

class ExchangesController < ApplicationController
  def create
    @accommodation = Accommodation.find(params[:exchange][:accommodation_id])
    @exchange = Exchange.new(exchange_params)
    if @exchange.save
      @exchange.create_modality(current_user.accommodation)
      @exchange.create_modality(@accommodation)
      redirect_to edit_exchange_path(@exchange)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @exchange = Exchange.find(params[:id])
    @message = Message.new
    @exchange_modalities = Modality.where(exchange: @exchange)
    @my_modality = @exchange.find_my_modality(current_user)
    @other_user_modality = @exchange.find_other_user_modality(current_user)
    @other_user = @exchange.find_other_user(current_user)
    find_my_exchanges
    @exchanges_infos = Exchange.build_exchanges_info(current_user)

    @occurence = @my_modality.find_last_input
    progress_toggle
    # raise
  end

  def show
    @exchange = Exchange.find(params[:id])
    @review = Review.new
    @date_today = Date.today
    @my_modality = @exchange.find_my_modality(current_user)
    @other_user_modality = @exchange.find_other_user_modality(current_user)
    accommodation = @other_user_modality.accommodation
    @markers = [{
      lat: accommodation.latitude,
      lng: accommodation.longitude,
      info_window_html: render_to_string(partial: "info_window", locals: { accommodation: accommodation }),
      marker_html: render_to_string(partial: "marker", locals: { accommodation: accommodation })
    }]
  end

  private

  def find_my_exchanges
    @my_exchanges = current_user.accommodation.modalities.map(&:exchange)
  end

  def exchange_params
    params.require(:exchange).permit(
      :check_in,
      :check_out,
      :duration
    )
  end

  def progress_toggle
    if @my_modality.progress == "pending"
      @my_modality.progress = "next"
    end
  end
end

app/views/exchanges/_exchanges_infos.html.erb
<div class="row">
  <div class="col-3">
    <h4><br>Messages<br></h4>
    <div class="messages-container">
      <% @exchanges_infos.each do |exchange| %>
        <%= link_to edit_exchange_path(exchange[0]) do %>
          <div class="div p-3 <%= exchange[0] == @exchange ? 'active' : '' %>">
            <div class="d-flex align-items-center">
              <%= cl_image_tag exchange[1].photo.key, crop: :fill, class: "avatar mr-3" %>
              <div class="div-left">
                <div class="name-msg-left"><%= exchange[1].first_name %></div>
                <div class="msg-left"><%=  raw(exchange[2]) %></div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

app/views/exchanges/_info_window.html.erb
<div class="info-map-window">
  <%= link_to accommodation_path(accommodation), style: "outline: none;" do %>
      <%= cl_image_tag accommodation.photos[0].key, height: 130, width: 220, crop: :fill %>
      <h6 class="title"><%= accommodation.title %></h6>
      <h6> 📍 <%= accommodation.address %> </h6>
  <% end %>
</div>

app/views/exchanges/_marker.html.erb
<%= cl_image_tag accommodation.user.photo.key, class: "avatar-map"%>

app/views/exchanges/_modality_form.html.erb
      <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
        <li class="nav-item" role="presentation">
          <button class="nav-link active" id="pills-currentuser-tab" data-bs-toggle="pill" data-bs-target="#currentuser" type="button" role="tab" aria-controls="pills-currentuser" aria-selected="true"><%= current_user.first_name %></button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="nav-link" id="pills-otheruser-tab" data-bs-toggle="pill" data-bs-target="#otheruser" type="button" role="tab" aria-controls="pills-otheruser" aria-selected="false"><%= @other_user.first_name %></button>
        </li>
      </ul>

      <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="currentuser" role="tabpanel" aria-labelledby="currentuser-tab">
            <%= simple_form_for(@my_modality, as: :modality, method: :patch, url: modality_path(@my_modality), data: { controller: 'flatpickr' }) do |f|%>
          <div class="accordion" id="accordionExample">
            <% @modality_form.each_with_index do |element, index| %>
              <div class="accordion-item">
                <h2 class="accordion-header" id="heading<%=index%>">

                  <% if @my_modality.progress == "pending" && index == @index_first_empty_input%>

                  <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse<%=index%>" aria-expanded="true" aria-controls="collapse<%=index%>">
                    <%= "#{element}" %>
                  </button>
                </h2>
                <div id="collapse<%=index%>" class="accordion-collapse collapse show" aria-labelledby="heading<%=index%>" data-bs-parent="#accordionExample">
                  <div class="accordion-body">
                    <% if element == "check_in" %>
                      <%= f.input "#{element}".to_sym, as: :string, label: false,  input_html: { data: { flatpickr_target: "checkIn" } } %>
                    <% else %>
                        <%= f.input "#{element}".to_sym, label: false%>
                    <% end %>
                  </div>
                </div>

                  <% else %>
                  <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse<%=index%>" aria-expanded="false" aria-controls="collapse<%=index%>">
                    <%= "#{element}" %>
                  </button>
                </h2>
                <div id="collapse<%=index%>" class="accordion-collapse collapse" aria-labelledby="heading<%=@modality_input_counter%>" data-bs-parent="#accordionExample">
                  <div class="accordion-body">
                    <% if element == "check_in" %>
                      <%= f.input "#{element}".to_sym, as: :string, label: false,  input_html: { data: { flatpickr_target: "checkIn" } } %>
                    <% else %>
                      <%= f.input "#{element}".to_sym, label: false%>
                      <%= @my_modality.id %>
                    <% end %>
                  </div>
                </div>

                  <% end %>
              </div>

            <% end%>
          </div>
            <%= f.hidden_field :progress%>
            <div class="separator">
            </div>
            <%= f.submit "+ Submit" %>
            <div class="separator">
            </div>
          <% end %>
        </div>

        <div class="tab-pane fade" id="otheruser" role="tabpanel" aria-labelledby="otheruser-tab">
          <%= simple_form_for(@other_user_modality, as: :modality, method: :patch, url: modality_path(@other_user_modality), data: { controller: 'flatpickr' }) do |f|%>
          <div class="accordion" id="accordionExample">
            <div class="accordion-item">
              <h2 class="accordion-header" id="headingOne">
                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                  Step 1
                </button>
              </h2>
              <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                <div class="accordion-body">
                  <%= f.input :duration, placeholder: "How long do you want to exchange ?" %>
                </div>
              </div>
            </div>
            <div class="accordion-item">
              <h2 class="accordion-header" id="headingTwo">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                  Step 2
                </button>
              </h2>
              <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
                <div class="accordion-body">
                  <%= f.input :check_in, as: :string, label: 'Choose your dates ! 🗓', placeholder: "Pick your dates !",  input_html: { data: { flatpickr_target: "checkIn" } } %>
                </div>
              </div>
            </div>
            <div class="accordion-item">
              <h2 class="accordion-header" id="headingThree">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                Step 3
                </button>
              </h2>
              <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
                <div class="accordion-body">
                  <%= f.input :keys, placeholder: "How about the keys ? 🗝" %>
                </div>
              </div>
            </div>
            <div class="accordion-item">
              <h2 class="accordion-header" id="headingFour">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
                Step 4
                </button>
              </h2>
              <div id="collapseFour" class="accordion-collapse collapse" aria-labelledby="headingFour" data-bs-parent="#accordionExample">
                <div class="accordion-body">
                  <%= f.input :petsitting, placeholder: "Can you take care of your host's pet ? 🐶" %>
                </div>
              </div>
            </div>
            <div class="accordion-item">
              <h2 class="accordion-header" id="headingFive">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
                Step 5
                </button>
              </h2>
              <div id="collapseFive" class="accordion-collapse collapse" aria-labelledby="headingFive" data-bs-parent="#accordionExample">
                <div class="accordion-body">
                  <%= f.input :transportation, placeholder: "Does your host can use your transportation ? 🚲" %>
                </div>
              </div>
            </div>
            <div class="accordion-item">
              <h2 class="accordion-header" id="headingSix">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseSix" aria-expanded="false" aria-controls="collapseSix">
                Step 6
                </button>
              </h2>
              <div id="collapseSix" class="accordion-collapse collapse" aria-labelledby="headingSix" data-bs-parent="#accordionExample">
                <div class="accordion-body">
                  <%= f.input :others, placeholder: "Anything else to tell your colleague ? 🤔" %>
                </div>
              </div>
            </div>
          </div>
            <%= f.hidden_field :progress%>
            <div class="separator">
            </div>
            <%= f.submit "+ Submit" %>
            <div class="separator">
            </div>
          <% end %>
        </div>

      </div>

app/views/exchanges/edit.html.erb
<%= render "components/navbar" %>

<div class="container-msg">
  <div class="row" data-controller="exchange-subscription"
       data-exchange-subscription-exchange-id-value="<%= @exchange.id %>"
       data-exchange-subscription-current-user-id-value="<%= current_user.id %>">

    <%= render "exchanges/exchanges_infos", exchanges_infos: @exchanges_infos, exchange: @exchange %>

    <div class="chatroom col-5">
      <h4><br>Talk to <%= @other_user.first_name %> ... <br><br> </h4>
      <% if @my_modality.exchange.messages.first.present? %>
        <div class="flex-msg-input">
          <div class="messages" data-exchange-subscription-target="messages" style="max-height: 540px; overflow-y: auto;">
            <% @exchange.messages.each do |message| %>
              <% if (message.form? && message.user != current_user) %>
                <%= render "messages/message", message: message, modality: @my_modality, occurence: @occurence %>
              <% elsif !(message.form? && message.user == current_user) %>
                <%= render "messages/message", message: message, modality: nil %>
              <% end %>
              <%# if (message.category == 0 && message.user != current_user) %>
                <%#= render "messages/message", message: message, modality: @my_modality %>
              <%# elsif !(message.category == 1 && message.user == current_user) %>
                <%#= render "messages/message", message: message, modality: nil %>
              <%# end %>
            <% end %>
          </div>
        </div>
      <% else %>
        <div class="messages" data-exchange-subscription-target="messages" style="max-height: 540px; overflow-y: auto;">
        </div>
      <% end %>
      <div class="msg-input">
        <%= simple_form_for [@exchange, @message],
        html: { data: { action: "turbo:submit-end->exchange-subscription#resetForm" }, class: "d-flex" } do |f|%>
          <%= f.input :content, placeholder: "Type something", label: false, autocomplete: false, wrapper_html: {class: "flex-grow-1"} %>
          <%= f.submit "Send", class: "btn btn-primary mb-3" %>
        <% end %>
      </div>
    </div>


    <div class="col-4">
      <h4><br>... Shape your exchange <br><br></h4>
      <%= render "modalities/modality_form", modality: @my_modality, other_user: @other_user, occurence: @occurence %>

      <%# <div class="link-validate"> %>
        <%# <%= link_to "Validate exchange", exchange_path(@exchange) %>
      <%# </div> %>

    </div>
  </div>
</div>

app/views/exchanges/index.html.erb
<%# <%= render "components/navbar" %>

<% @my_exchanges.each do |exchange| %>
  <%= exchange.id %>
<% end %>

app/views/exchanges/show.html.erb
<%= render 'components/navbar' %>
<div class="banner about" style="background-image: linear-gradient(rgba(0,0,0,0.6),rgba(0,0,0,0.6)), url(<%= cl_image_path @other_user_modality.accommodation.photos.first.key, height: 340, width: 560, crop: :fill %>)">
    <div class="banner-lp about valid">
      <h1>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;🎉 You are ready to exchange !</h1>
    </div>
</div>


<div class="all-final">
  <div class="flex-all-infos-valid">
    <div class="flex-exchange-first-block">
      <div class="flex-buddies-info-main-infos">
          <h4> Accommodation infos</h4>
        <div style="width: 100%; height: 340px;"
          data-controller="map"
          data-map-markers-value="<%= @markers.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>

        <div class="acco-details-valid-final">
          <h5> 🏠<b>&nbsp;&nbsp;&nbsp;Where you'll stay</b></h5>
          <div class="highlight-valid">
            <p><i class="fa-solid fa-location-dot"></i>&nbsp;&nbsp;&nbsp;<b>Address</b></p>
            <p> <%= @other_user_modality.accommodation.address %></p>
          </div>
          <div class="highlight-valid">
            <p><i class="fa-solid fa-person-shelter"></i>&nbsp;&nbsp;&nbsp; <b>Number of bedrooms</b></p>
            <p><%= @other_user_modality.accommodation.nb_of_bedrooms %> bedrooms</p>
          </div>
          <div class="highlight-valid">
            <p><i class="fa-solid fa-bed"></i> &nbsp;&nbsp;&nbsp;<b>Number of beds</b></p>
            <p><%= @other_user_modality.accommodation.nb_of_beds %> beds</p>
          </div>
          <div class="highlight-valid">
            <p><i class="fa-solid fa-shower"></i> &nbsp;&nbsp;&nbsp;<b>Number of bathrooms</b></p>
            <p><%= @other_user_modality.accommodation.nb_of_bathrooms %> bathrooms</p>
          </div>
        </div>
      </div>
    </div>
    <div class="flex-main-validate">
          <h4> Exchange infos</h4>
          <div class="main-infos-block1">
            <h5>🗝️<b>&nbsp;&nbsp;&nbsp;Main infos</b></h5>
              <div class="flex-valid-exchange-main-infos">
                <div class="valid-block valid-exchange-duration">
                  <h6><i class="fa-solid fa-calendar"></i><b> &nbsp;&nbsp;Duration</b></h6>
                  <p><%= @my_modality.duration %> days</p>
                </div>
                <div class="valid-block valid-exchange-arrival">
                  <h6><i class="fa-solid fa-plane-arrival"></i><b> &nbsp;&nbsp;Arrival</b></h6>
                  <p><%= @my_modality.check_in %></p>
                </div>
                <div class="valid-block valid-block-last valid-exchange-departure">
                  <h6><i class="fa-solid fa-plane-departure"></i><b> &nbsp;&nbsp;Departure</b></h6>
                  <p><%= @my_modality.check_out %></p>
                </div>
              </div>
            </div>

            <div class="flex-secondary-infos-valid">
                <ul class="nav nav-tabs" id="myTab" role="tablist">
                  <li class="nav-item" role="presentation">
                    <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home-tab-pane" type="button" role="tab" aria-controls="home-tab-pane" aria-selected="true">My preferences</button>
                  </li>
                  <li class="nav-item" role="presentation">
                    <button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile-tab-pane" type="button" role="tab" aria-controls="profile-tab-pane" aria-selected="false"><%= @other_user_modality.accommodation.user.first_name %>'s preferences</button>
                  </li>
                </ul>
                <div class="tab-content" id="myTabContent">
                  <div class="tab-pane fade show active" id="home-tab-pane" role="tabpanel" aria-labelledby="home-tab" tabindex="0">
                    <div class="flex-me">
                      <div class="flex-picture-buddy-valid 1">
                        <%= cl_image_tag current_user.photo.key, crop: :fill, class: "avatar mr-3 msg valid" %>&nbsp;&nbsp;
                        <h6> <b> <%= current_user.first_name %> <%= current_user.last_name.upcase %> </h6> </b>
                      </div>
                      <div class="valid-exchange-secondary-infos my">
                        <div class="valid-block valid-exchange-keys">
                          <h6><b><i class="fa-solid fa-key"></i> &nbsp;&nbsp;Keys</b></h6>
                          <p> <%= @my_modality.keys %> </p>
                        </div>
                        <div class="valid-block valid-exchange-petsitting">
                          <h6><i class="fa-solid fa-paw"></i> <b> &nbsp;&nbsp;Petsitting</b></h6>
                          <p> <%= @my_modality.petsitting %></p>
                        </div>
                        <div class="valid-block valid-exchange-transportation">
                          <h6><i class="fa-solid fa-bicycle"></i><b> &nbsp;&nbsp;Transportation</b></h6>
                          <p><%= @my_modality.transportation %></p>
                        </div>
                        <div class="valid-block valid-block-last valid-exchange-others">
                          <h6><i class="fa-solid fa-suitcase"></i><b> &nbsp;&nbsp;Others</b></h6>
                          <p> <%= @my_modality.others %> </p>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="tab-pane fade" id="profile-tab-pane" role="tabpanel" aria-labelledby="profile-tab" tabindex="0"><div class="flex-him">
                    <div class="flex-picture-buddy-valid 1">
                      <%= cl_image_tag @other_user_modality.accommodation.user.photo.key, crop: :fill, class: "avatar mr-3 msg valid" %>&nbsp;&nbsp;
                      <h6> <b><%= @other_user_modality.accommodation.user.first_name %> <%= @other_user_modality.accommodation.user.last_name.upcase %> </h6> </b>
                    </div>
                    <div class="valid-exchange-secondary-infos him">
                      <div class="valid-block valid-exchange-keys">
                        <h6><b><i class="fa-solid fa-key"></i> &nbsp;&nbsp;Keys</b></h6>
                        <p> <%= @other_user_modality.keys %> </p>
                      </div>
                      <div class="valid-block valid-exchange-petsitting">
                        <h6><i class="fa-solid fa-paw"></i><b> &nbsp;&nbsp;Petsitting</b></h6>
                        <p> <%= @other_user_modality.petsitting %></p>
                      </div>
                      <div class="valid-block valid-exchange-transportation">
                        <h6><i class="fa-solid fa-bicycle"></i><b> &nbsp;&nbsp;Transportation</b></h6>
                        <p><%= @other_user_modality.transportation %></p>
                      </div>
                      <div class="valid-block valid-block-last valid-exchange-others">
                        <h6><i class="fa-solid fa-suitcase"></i><b> &nbsp;&nbsp;Others</b></h6>
                        <p> <%= @other_user_modality.others %> </p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

      <div class="container-accommodation-form review">
        <div class="accommodation-form review-main">
          <div class="accommodation-text">
              <div class="container-accommodation-form review">
                <% if @other_user_modality.review.nil? && @date_today > @my_modality.check_out%>
                <div class="container">
                  <h4>Comment your exchange :</h4>
                    <%= simple_form_for [@other_user_modality, @review], method: :post, url: modality_reviews_path(@other_user_modality) do |f|%>
                    <%= f.hidden_field :user_id, value: current_user.id %>
                    <%= f.hidden_field :modality_id, value: @other_user_modality.id %>
                    <%= f.input :content %>
                    <%= f.submit "Publish comment" %>
                  <% end %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>


<%= render 'components/footer' %>