config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '/about', to: 'about#show'
  resources :users, only: %i[show update edit destroy]
  resources :accommodations do
    resources :exchanges, only: %i[create]
  end

  resources :exchanges, only: %i[index edit show] do
    resources :modalities, only: %i[create]
    resources :messages, only: %i[create]
  end

  resources :modalities, only: %i[update progress] do
    resources :reviews, only: %i[create update edit]
  end
end

app/models/accommodation.rb
class Accommodation < ApplicationRecord
  belongs_to :user
  has_many :modalities, dependent: :destroy
  has_many :exchanges, through: :modalities
  has_many_attached :photos

  validates :title, presence: true
  validates :description, presence: true
  validates :address, presence: true
  validates :nb_of_guests, presence: true
  validates :nb_of_bedrooms, presence: true
  validates :nb_of_beds, presence: true
  validates :nb_of_bathrooms, presence: true
  validates :garden, inclusion: { in: [true, false] }
  validates :swimming_pool, inclusion: { in: [true, false] }
  validates :balcony, inclusion: { in: [true, false] }
  validates :nb_of_tvs, presence: true
  validate :validate_at_least_one_photo

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def validate_at_least_one_photo
    errors.add(:photos, ": You must upload at least 1 photo !") if photos.blank?
  end
end

app/controllers/accommodations_controller.rb
class AccommodationsController < ApplicationController
  def index
    # @accommodations = Accommodation.all
    @accommodations = Accommodation.all
    if params[:query].present?
      @accommodations = @accommodations.near(params[:query].to_s, 2000).all
    end
    @markers = @accommodations.geocoded.map do |accommodation|
      {
        lat: accommodation.latitude,
        lng: accommodation.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { accommodation: accommodation }),
        marker_html: render_to_string(partial: "marker", locals: { accommodation: accommodation })
      }
    end
  end

  def show
    @accommodation = Accommodation.find(params[:id])
    @exchange = Exchange.new
    @modalities = Modality.where("accommodation_id = ?", @accommodation.id)
    @reviews = []
    @modalities.each do |modality|
      @reviews << modality.review unless modality.review.nil?
    end
  end

  def edit
    @accommodation = current_user.accommodation
  end

  def update
    @accommodation = current_user.accommodation
    if @accommodation.update(accommodation_params)
      redirect_to @accommodation, notice: "Infos has been updated !"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def accommodation_params
    params.require(:accommodation).permit(:title,
                                          :description,
                                          :nb_of_guests,
                                          :nb_of_bathrooms,
                                          :nb_of_bedrooms,
                                          :nb_of_beds,
                                          :garden,
                                          :swimming_pool,
                                          :balcony,
                                           photos: [])
  end
end

app/views/accommodations/_form.html.erb
<%= simple_form_for @accommodation, url: "/accommodations/#{@accommodation.id})", method: :patch do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :address,
      input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
      wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
    %>
    <%= f.input :nb_of_guests %>
    <%= f.input :nb_of_bedrooms %>
    <%= f.input :nb_of_beds %>
    <%= f.input :nb_of_bathrooms %>
    <%= f.input :garden %>
    <%= f.input :balcony %>
    <%= f.input :swimming_pool %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>

    <%= f.submit "Enregistrer les modifications" %>
<% end %>

app/views/accommodations/_info_window.html.erb
<div class="info-map-window">
  <%= link_to accommodation_path(accommodation), style: "outline: none;" do %>
      <%= cl_image_tag accommodation.photos[0].key, height: 130, width: 220, crop: :fill %>
      <h6 class="title"><%= accommodation.title %></h6>
      <h6><i class="fa-solid fa-user"></i> &nbsp;<%= accommodation.user.first_name %> | <%= accommodation.user.job %> </h6>
      <h6> <i class="fa-solid fa-house"></i> &nbsp;<%= accommodation.nb_of_guests %> people </h6>
  <% end %>
</div>

app/views/accommodations/edit.html.erb
<%= render 'components/navbar' %>
<div class="super-accommodation-form">
  <div class="image-container-login">
    <%= image_tag "edit-form.png", class: "logo-img" %>
  </div>
  <div class="accommodation-form">
    <div class="accommodation-text">
      <h2>Modifier les informations du logement</h2>
      <%= render 'form' %>
    </div>
  </div>
</div>
<%= render 'components/footer' %>

app/views/accommodations/index.html.erb
<div class="navbar-lp">
  <%= render 'components/navbar' %>
</div>
<div class="wrapper">
  <div class="search_lp">


<%# main hp banner %>
<div class="banner lp" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1523301343968-6a6ebf63c672?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1769&q=80);">
  <div class="container">
    <%# search %>
    <%= render 'components/search' %>
  </div>
</div>

<div class="main-container-lp">


  <div class="map-accommodations-lp">
    <div class="container lp">
      <div class="container-all-accommodations">
        <div class="title-subtitle">
          <h4>All Accommodations</h4>
          <p>More than <%= @accommodations.size %> accommodations available.</em></p>
        </div>
        <%= render 'components/card' %>
      </div>
    </div>

    <div class="map-container">
      <div class="map-wraper">
        <div style="width: 100%; height: 800px;"
          data-controller="map"
          data-map-markers-value="<%= @markers.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
    </div>
  </div>
</div>

<%= render 'components/footer' %>

app/views/accommodations/show.html.erb
<%= render 'components/navbar' %>

<%# product page %>
<div class="wrapper">
  <div class="main-container-pp">
    <div class="container-pp">
      <div class="container">
        <div class="container-first-infos">
          <h1><%= @accommodation.title %></h1>
          <h5><%=@accommodation.address %> · <%= @accommodation.nb_of_guests %> guests</h5>
        </div>
        <div class="photos-accommodation-index">
          <div class="main-photo">
          <button data-bs-toggle="modal" data-bs-target="#exampleModal">
            <%= cl_image_tag @accommodation.photos.first.key, height: 610, width: 810, crop: :fill, class: "image-clickable" %>
          </button>
          <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <%= cl_image_tag @accommodation.photos.first.key, height: 610, width: 810, crop: :fill, class: "image-clickable" %>
                </div>
              </div>
            </div>
          </div>
          <div class="secondary-photos">
            <% @accommodation.photos[1..-1].each do |photo| %>
              <div class="secondary-photo">
                <button data-bs-toggle="modal" data-bs-target="#photoModal<%= photo.id %>">
                  <%= cl_image_tag photo.key, height: 300, width: 500, crop: :fill, class: "image-clickable" %>
                </button>
                <div class="modal fade" id="photoModal<%= photo.id %>" tabindex="-1" aria-labelledby="photoModalLabel<%= photo.id %>" aria-hidden="true">
                  <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <%= cl_image_tag photo.key, height: 610, width: 810, crop: :fill, class: "image-clickable" %>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
        <% if current_user == @accommodation.user %>
          <%= link_to edit_accommodation_path(@accommodation), method: :get do %>
            <p id="edit">Edit <i class="fa-solid fa-pen-to-square"></i></p>
          <% end %>
        <% end %>
        <div class="flex-pp-details-booking">
          <div class="container-pp-details-block1">
            <div class="pp-details">
              <div class="user-bio">
                <div class="desc-user">
                  <div class="flex-photo-user-name">
                    <h5><%= @accommodation.user.first_name %> <%= @accommodation.user.last_name.upcase %></h5>
                    <% if @accommodation.user.photo.key == nil%>
                      <%= image_tag "avatar_default.jpg", height: 50, width: 50, crop: :fill, class: "avatar-pp dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                    <% else %>
                      <%= cl_image_tag @accommodation.user.photo.key, height: 50, width: 50, crop: :fill, class: "avatar-pp dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                    <% end %>
                  </div>
                  <div class="separator"></div>
                    <h5>About me</h5>
                  <p><%= @accommodation.user.bio %></p>
                  <div class="flex-container">
                    <div class="user-item user-1">
                      <i class="fa-solid fa-briefcase"></i><p><%= @accommodation.user.job %> </p>
                    </div>
                    <div class="user-item user-2">
                      <i class="fa-solid fa-calendar"></i><p><%= @accommodation.user.seniority %> years of services </p>
                    </div>
                    <div class="user-item user-3">
                      <i class="fa-solid fa-building"></i><p><%= @accommodation.user.company.name %> </p>
                    </div>
                  </div>
                </div>
              </div>
              <div class="acc-desc">
              <div class="separator"></div>
                <h5>Where you'll stay</h5>
                <p><%= @accommodation.description %></p>
              </div>
            </div>
          </div>
          <div class="flex-container-review">
            <div class="container-booking-block2">
              <% if @reviews.length == 0 %>
                <h5><%= @accommodation.user.first_name %> has never done an exchange.<br> Be the first ! 🗝️</h5>
              <% else %>
              <h5><%= @accommodation.user.first_name %> has already done <%= pluralize(@reviews.length, 'exchange') %></h5>
              <% @reviews.each do |review| %>
                <div>
                  <div class="separator">
                  </div>
                  <div class="main-infos-reviews">
                    <div class="photo-user-review">
                      <%= cl_image_tag review.user.photo.key, height: 50, width: 50, crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false  %>
                    </div>
                    <div class="name-duration-review">
                      <h6><%= review.user.first_name %></h6>
                      <p><%= review.user.job %> · Exchanged during <%= review.modality.duration %> days</p>
                    </div>
                  </div>
                  <div class="comment">
                    <p><%= review.content %></p>
                  </div>
                </div>
                <% end %>
              <% end %>
              </div>
              <div class="offer-button">
                <%= simple_form_for(@exchange, as: :exchange, method: :post, url: accommodation_exchanges_path(@accommodation)) do |f|%>
                  <%= f.hidden_field :accommodation_id, value: @accommodation.id %>
                  <%= f.submit "Offer an exchange !" %>
                <% end %>
            </div>
          </div>
        </div>
        <div class="container-pp-details-block3">
          <div class="flex-container">
            <% if @accommodation.nb_of_bedrooms.present? %>
              <div class="equipement-item equipement-1">
                <i class="fa-solid fa-person-shelter"></i><p><%= @accommodation.nb_of_bedrooms %> bedrooms </p>
              </div>
            <% end %>
            <% if @accommodation.nb_of_beds.present? %>
              <div class="equipement-item equipement-2">
                <i class="fa-solid fa-bed"></i><p><%= @accommodation.nb_of_beds  %> beds </p>
              </div>
            <% end %>
            <% if @accommodation.nb_of_bathrooms.present? %>
              <div class="equipement-item equipement-3">
                <i class="fa-solid fa-shower"></i><p><%= @accommodation.nb_of_bathrooms %> bathrooms </p>
              </div>
            <% end %>
            <% if @accommodation.garden.present? %>
              <div class="equipement-item equipement-4">
                <i class="fa-solid fa-tree"></i><p><% @accommodation.garden %> Garden </p>
              </div>
            <% end %>
            <% if @accommodation.swimming_pool.present? %>
              <div class="equipement-item equipement-5">
                <i class="fa-solid fa-water-ladder"></i><p><% @accommodation.swimming_pool %> Swimming pool </p>
              </div>
            <% end %>
            <% if @accommodation.balcony.present? %>
              <div class="equipement-item equipement-6">
                <i class="fa-solid fa-tree-city"></i><p><% @accommodation.balcony %> Balcony </p>
              </div>
            <% end %>
            <% if @accommodation.nb_of_tvs.present? %>
              <div class="equipement-item equipement-7">
                <i class="fa-solid fa-tv"></i><p><%= @accommodation.nb_of_tvs %> TV </p>
              </div>
            <% end %>
          </div>
        </div>
    </div>
  </div>
</div>


<%= render 'components/footer' %>